audit_header: false
title: Clarksville Real Estate Video Blog with Kenneth Adams
description: Our mission at Ken Adams Real Estate Team is to be your best resource for Clarksville real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Ken Adams Real Estate Team, your professional Clarksville Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Kenneth Adams
  title:
  license_number:
  about_markdown: |
    I am Ken Adams, a native of Springfield, TN, I have lived in Clarksville for 15 years. I have been a realtor for 12 years, and during that time I have had the pleasure of helping countless people find their dream home. I firmly believe in giving back to our community and serving others. I am a people person and I truly value your time. I greatly value family, and I want to help you and yours. Whether you are buying, selling, or investing, it’s my personal promise that my team and I will work hard for you and always give you our best effort. We value you, we care about you, and we want to be your Realtors For Life!
  brand: Ken Adams Real Estate Team
  brokerage:
  market: Keller Williams
  address: 2271 Wilma Rudolph Blvd., Clarksville, TN 37040
  phone: 931-249-0514
  phone_type:
  phone2:
  phone2_type:
  email: kadams@kw.com
  url: http://kenadamsteam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://allhomesinclarksville.com/selling
  second_CTA_text: Home Search
  second_CTA_URL: https://allhomesinclarksville.com/search#?q_limit=36&mlsId=77&status=1|3&q_sort=createdAt-&q_offset=0

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Clarksville Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://allhomesinclarksville.com/selling

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Clarksville Home?"
    CTA_text2: "Search the entire MLS for your Clarksville home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://allhomesinclarksville.com/search#?q_limit=36&mlsId=77&status=1|3&q_sort=createdAt-&q_offset=0

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/kenadamsteam
  linkedin_url: http://www.linkedin.com/pub/ken-adams/8/442/b95
  youtube_url: https://www.youtube.com/channel/UC51AiSjgW_KHXZp7anM6Gsw?disable_polymer=true
  twitter_url: http://www.twitter.com/kenadamsteam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Clarksville Real Estate Podcast with Kenneth Adams'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Clarksville Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Ken Adams Real Estate Team - your professional Clarksville Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Clarksville, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kenneth Adams'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: Clarksville Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#c32033'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
